### ISSUE TITLE
Not working in Firefox & Chromium (Linux)

### ISSUE THREAD

**Issue by freehuntx** [dmotz/trystero#38]
For some reason trystero stopped working on (Linux) Firefox and Chromium for me.
Chrome works.
I tested the demo: https://oxism.com/trystero

**Comment by jeremyckahn** [comment]
It seems to be working on Firefox 111 on Ubuntu 22.04 for me. @freehuntx which distro are you using?

**Comment by freehuntx** [comment]
Fedora 35
- Version 105.0.5195.125 (Official Build) Fedora Project (64-bit)
- 107.0 (64-bit) Firefox

**Comment by jeremyckahn** [comment]
I just tested the demo in a Fedora 35 VM on Firefox 107, and it seems to work. It took roughly 20 seconds for the peers to connect, but I suspect that the delay is due to the virtualized nature of my environment.

@freehuntx do you know if anything related to your network connection has changed since you last saw the demo working? The demo does not appear to be using a TURN server, so there will be diminished connection success for some users.

**Comment by freehuntx** [comment]
This is super weird, its working on other devices for me aswell.
Maybe it is some plugin which does shenanigans. I will debug it further and reopen this issue if i got more informations.
Thanks for your time!
