### ISSUE TITLE
Question: relay list update frequency?

### ISSUE THREAD

**Issue by hchiam** [dmotz/trystero#88]
@dmotz, how often do you find or would expect that you'd have to update the list of relay URLs? i'm having fun building apps with trystero, but i'm thinking about how often i'd need to update my dependency on trystero for production. 

maybe every few months, based naively on the worst case with the nostr part of the commit history notes below?

but then again, i'm guessing it shouldn't be a concern for developers building with trystero, since i'd hope it's very unlikely that all the relay URLs listed in the array will fail/close at the same time.

commit history notes/observations: 
- the list in `src/nostr.js` had removals from its `defaultRelayUrls` in July a [couple](https://github.com/dmotz/trystero/commit/4cdfc8ce14d1fb53ffaabbc7bdf9ecb5879346af) [times](https://github.com/dmotz/trystero/commit/a5606ec47d12b9c44b300a728161fa63c0ffb4d4) and also [in April](https://github.com/dmotz/trystero/commit/4fe305988d0754304da541dcf602feed4da01342)
  - so every 3 months, if we naively assume past patterns could be repeated in the future?
- `src/torrent.js` had removals from its `defaultRelayUrls` in [February](https://github.com/dmotz/trystero/commit/7141033c7458697f4a1eacefeb25414e6e82a3d7) and [October a year ago in 2023](https://github.com/dmotz/trystero/commit/79c5eb8de4d9b330763d83458773f95796475a03) and removals from its `defaultTrackerUrls` in [February](https://github.com/dmotz/trystero/commit/b46fe9cd5b4da835fdc23a530d1e654c1d9b21aa) and in [October a few years ago in 2021](https://github.com/dmotz/trystero/commit/39c1e5240a8614d0155705894cbb030978b783d0)
  - so every year?
- (`src/ifps.js` only had an explicit `bootstrapPeers` list added [in July](https://github.com/dmotz/trystero/commit/e242085b258c5117885b561d334d8ee81a05a32e))
- (`src/mqtt.js` only had the order of its `defaultRelayUrls` updated, which it had [since February](https://github.com/dmotz/trystero/commit/84805e295e659b3409d1db42c81b3ea6ad6f154c))
- (`src/peer.js` had `defaultIceServers` set up [in March](https://github.com/dmotz/trystero/commit/453381fdf561c668ff07c347567fb2376471b0a3) and had no removals so far, only an _addition_ [in July](https://github.com/dmotz/trystero/commit/4af94b7a434ff22e5cb32444cdb56237817396be)

**Comment by hchiam** [comment]
to be clear, from what i recall, there has been at least 1 relay URL for nostr and for torrent that hasn't changed since the arrays have been created in the commit history up to the time of writing, but i feel a little concerned seeing the lists having a lot of the URLs removed or changed so far

**Comment by dmotz** [comment]
I usually check the relay lists when I cut a new release and prune ones that look to be failing. You can try this yourself by cloning the repo and running `npm run test-relays`.

Nostr has by far the most relays available (which is why it's the default) and if you're really concerned about redundancy you can pass a higher number for `relayRedundancy` in the room config object. The Nostr strategy defaults to 5 which is already quite a bit of redundancy. A more advanced option would be passing your own custom list of relays (as `relayUrls`) and you can find a huge amount of relays listed on [nostr.watch](https://legacy.nostr.watch/relays/find). Just be sure to test them as some relays limit what you're allowed to do. Finally, you can always run your own Nostr relay on a server to have an extra layer of control over uptime.

Hope this helps.
